In [101]:
import sklearn
# We are gonna use Scikit's LinearRegression model
from sklearn.linear_model import LinearRegression

# Your input data, X and Y are lists (or Numpy Arrays)
x = [[2,4],[3,6],[4,5],[6,7],[3,3],[2,5],[5,2]]
y = [14,21,22,32,15,16,19]

x

[[2, 4], [3, 6], [4, 5], [6, 7], [3, 3], [2, 5], [5, 2]]

In [102]:

y = np.array(y)
x = np.array(x)

In [103]:
x

array([[2, 4],
       [3, 6],
       [4, 5],
       [6, 7],
       [3, 3],
       [2, 5],
       [5, 2]])

In [104]:
y

array([14, 21, 22, 32, 15, 16, 19])

In [105]:
# Initialize the model then train it on the data
import numpy as np
genius_regression_model = LinearRegression()
genius_regression_model.fit(x,y)
y_pred = genius_regression_model.predict(x)
# Predict the corresponding value of Y for X = [8,4]
# print(genius_regression_model.predict([8,4]))

In [108]:
genius_regression_model.predict(np.array([[8,4]]))
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
print(mean_squared_error(y,y_pred))
print(np.sqrt(mean_squared_error(y,y_pred)))
print(np.log(np.sqrt(mean_squared_error(y,y_pred))))
print(mean_absolute_error(y,y_pred))
print(r2_score(y,y_pred))

5.409331921515509e-30
2.325797050801189e-15
-33.69471359707098
1.522591576628786e-15
1.0


In [110]:
def adjusted_r2_score(actual, predictions, num_pred, num_samples):
    n = num_samples
    k = num_pred
    r2 = r2_score(actual, predictions)
    adjusted_r2 = 1 - ((1-r2) * ((n-1)/(n-k-1)))
    return adjusted_r2
adjusted_r2_score(y,y_pred,x.shape[0],x.shape[1])

1.0

In [111]:
y

array([14, 21, 22, 32, 15, 16, 19])

In [112]:
y_pred

array([14., 21., 22., 32., 15., 16., 19.])

In [116]:
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures

x = [[1],[4],[7],[13],[10]]
# x = x.reshape(-1,1)
# Y1 = 10 + 6*x
y1 = np.array([16, 34, 52, 88, 70])
# Y2 = x*x = x^2
y2 = [1, 16, 49, 169, 100]
poly  = PolynomialFeatures(degree = 2)
poly_x = poly.fit_transform(x)
poly_x







array([[  1.,   1.,   1.],
       [  1.,   4.,  16.],
       [  1.,   7.,  49.],
       [  1.,  13., 169.],
       [  1.,  10., 100.]])

In [118]:
genius_regression_model = LinearRegression()
genius_regression_model.fit(poly_x, y1)
y_pred = genius_regression_model.predict(poly_x)
print(mean_squared_error(y1,y_pred))
print(np.sqrt(mean_squared_error(y1,y_pred)))
print(np.log(np.sqrt(mean_squared_error(y1,y_pred))))
print(mean_absolute_error(y1,y_pred))
print(r2_score(y1,y_pred))
print(adjusted_r2_score(y1,y_pred,poly_x.shape[0],poly_x.shape[1]))

1.5045155184375138e-27
3.8788084748251156e-14
-30.88066328956175
3.2684965844964606e-14
1.0
1.0


In [119]:
y2 = [1, 16, 49, 169, 100]

# This will convert X into 
# [[1,1], [4,16], [7,49], .. etc]
# Only 1st and 2nd degree, since degree=2
pf = PolynomialFeatures(degree=2)
poly_x = pf.fit_transform(x)

genius_regression_model.fit(poly_x, y2)
genius_regression_model = LinearRegression()
genius_regression_model.fit(poly_x, y2)
y_pred = genius_regression_model.predict(poly_x)
print(mean_squared_error(y2,y_pred))
print(np.sqrt(mean_squared_error(y2,y_pred)))
print(np.log(np.sqrt(mean_squared_error(y2,y_pred))))
print(mean_absolute_error(y2,y_pred))
print(r2_score(y2,y_pred))
print(adjusted_r2_score(y2,y_pred,poly_x.shape[0],poly_x.shape[1]))

8.36586989986883e-29
9.146512942028142e-15
-32.32540368749192
5.595524044110789e-15
1.0
1.0


In [127]:
x = [[1],[4],[7],[13],[10]]
y1 = [16, 34, 52, 88, 70]
y2 = [1, 16, 49, 169, 100]
from sklearn import svm
model = svm.SVR(kernel = 'poly')
model.fit(x,y1)
y_pred = model.predict(x)
print(mean_squared_error(y1,y_pred))
print(np.sqrt(mean_squared_error(y1,y_pred)))
print(np.log(np.sqrt(mean_squared_error(y1,y_pred))))
print(mean_absolute_error(y1,y_pred))
print(r2_score(y1,y_pred))
print(adjusted_r2_score(y1,y_pred,poly_x.shape[0],poly_x.shape[1]))

107.76084257031239
10.380792001110146
2.3399571755119783
7.949112974776344
0.833702403440876
1.1108650643727493


In [121]:
x = [[1],[4],[7],[13],[10]]
y1 = [16, 34, 52, 88, 70]
y2 = [1, 16, 49, 169, 100]
from sklearn import svm
model = svm.SVR(kernel='poly')
model.fit(x,y2)
y_pred = model.predict(x)
print(mean_squared_error(y2,y_pred))
print(np.sqrt(mean_squared_error(y2,y_pred)))
print(np.log(np.sqrt(mean_squared_error(y2,y_pred))))
print(mean_absolute_error(y2,y_pred))
print(r2_score(y2,y_pred))
print(adjusted_r2_score(y2,y_pred,poly_x.shape[0],poly_x.shape[1]))

111.79693868070667
10.573407146265893
2.358342089120755
8.08582179747286
0.9702255942578282
1.0198496038281146


###What to Look For
#R² close to 1? Great job! Your model explains most of the variation.
#Low MAE and RMSE? Your predictions are close to the actual values.
#Residuals all over the place? That’s good — no obvious pattern means the model is solid.
#Residuals showing a curve? Hmm, maybe the relationship isn’t linear after all (time to explore other models).
#And there you have it! 🚀 You’ve not only built a model but also evaluated its performance like a pro. If things didn’t go perfectly, don’t worry — it’s all part of the learning process. Up next, we’ll look at ways to tweak and improve your model. Keep going — you’re almost there! 💪